######################## default configuration ####################
baseURL = "https://www.cheshta.org.in/"
title = "Cheshta Foundation"
theme = "bigspring"

# post excerpt
summaryLength = "15"

# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

# post pagination
[pagination]
    pagerSize = "6"

# disqus short name
[services]
  [services.disqus]
    shortname = "" # get your shortname form here : https://disqus.com

