# main menu
[[main]]
name = "मुख्य पेज"
url = "/"
weight = 1
#
#[[main]]
#name = "सेवाए"
#url = "services"
#weight = 2
#
#[[main]]
#name = "प्रदर्शनी"
#url = "gallery"
#weight = 3
#
#[[main]]
#name = "प्रश्न-उत्तर"
#url = "faq"
#weight = 4
#
#[[main]]
#name = "समाचार"
#url = "news"
#weight = 5
#
[[main]]
name = "संपर्क"
url = "contact"
weight = 5
#
# footer menu left
#[[footer_left]]
#name = "About Us"
#url = "#"
#
#[[footer_left]]
#name = "Objectives"
#url = "#"
#
# footer menu middle
#[[footer_middle]]
#name = "Services"
#url = "services"
#
#[[footer_middle]]
#name = "Infrastructure"
#url = "#"
#
# footer menu right
#[[footer_right]]
#name = "FAQ"
#url = "faq"
#
#[[footer_right]]
#name = "Contact Us"
#url = "contact"
