#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "Cheshta Foundation"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "Whatsapp"
icon = "fab fa-whatsapp" # themify icon : https://themify.me/themify-icons
link = "https://wa.me/919455529265"

[[social]]
title = "Telegram"
icon = "fab fa-telegram" # themify icon : https://themify.me/themify-icons
link = "https://t.me/cheshtafoundation"

[[social]]
title = "Email"
icon = "fa fa-envelope" # themify icon : https://themify.me/themify-icons
link = "mailto:info@cheshta.org.in"

